name: Build Android
on:
  push:
    branches: '*'
jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Show runner machine infomation
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo from master branch
        uses: actions/checkout@v3
      - name: Start the Docker container
        run: |
          docker run -d --name react-native-app-container -v ${{ github.workspace }}:/workspace reactnativecommunity/react-native-android:latest tail -f /dev/null
      - name: Build the React Native project
        run: docker exec react-native-app-container /bin/sh -c "cd /workspace/example && npm install && npx react-native clean && npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res"
      - name: Build the Android APK
        run: |
          docker exec react-native-app-container /bin/sh -c "cd /workspace/example/android && chmod +x gradlew && ./gradlew assembleRelease"
      - name: Stop and remove the Docker container
        run: |
          docker stop react-native-app-container && docker rm react-native-app-container
