name: Build Android
on:
  push:
    branches: [ "master" ]
jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Show runner machine infomation
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo from master branch
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Install npm dependency
        run: yarn install
      - name: Install npm dependency
        run: |
          cd example
          yarn install
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: cd android && ./gradlew build
      - name: Build Android JS Bundle
        run: |
          yarn run package-android
